services:
  web:
    build:
      context: .
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      VITE_SUPABASE_URL: ${VITE_SUPABASE_URL:-http://localhost}
      VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY:-anon-key-placeholder}
